services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "redispass",
      ] # enables persistence (AOF)
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  mongo_data:
  redis_data:

networks:
  backend:
